# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongodoc}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Les Hill"]
  s.date = %q{2009-12-09}
  s.description = %q{ODM for MongoDB}
  s.email = %q{leshill@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "data/.gitignore",
     "features/mongodb.yml",
     "features/mongodoc_base.feature",
     "features/saving_an_object.feature",
     "features/step_definitions/collection_steps.rb",
     "features/step_definitions/criteria_steps.rb",
     "features/step_definitions/document_steps.rb",
     "features/step_definitions/documents.rb",
     "features/step_definitions/json_steps.rb",
     "features/step_definitions/object_steps.rb",
     "features/step_definitions/objects.rb",
     "features/step_definitions/util_steps.rb",
     "features/support/support.rb",
     "features/using_criteria.feature",
     "lib/mongodoc.rb",
     "lib/mongodoc/attributes.rb",
     "lib/mongodoc/bson.rb",
     "lib/mongodoc/collection.rb",
     "lib/mongodoc/connection.rb",
     "lib/mongodoc/criteria.rb",
     "lib/mongodoc/cursor.rb",
     "lib/mongodoc/document.rb",
     "lib/mongodoc/ext/array.rb",
     "lib/mongodoc/ext/binary.rb",
     "lib/mongodoc/ext/boolean_class.rb",
     "lib/mongodoc/ext/date.rb",
     "lib/mongodoc/ext/date_time.rb",
     "lib/mongodoc/ext/dbref.rb",
     "lib/mongodoc/ext/hash.rb",
     "lib/mongodoc/ext/nil_class.rb",
     "lib/mongodoc/ext/numeric.rb",
     "lib/mongodoc/ext/object.rb",
     "lib/mongodoc/ext/object_id.rb",
     "lib/mongodoc/ext/regexp.rb",
     "lib/mongodoc/ext/string.rb",
     "lib/mongodoc/ext/symbol.rb",
     "lib/mongodoc/ext/time.rb",
     "lib/mongodoc/parent_proxy.rb",
     "lib/mongodoc/proxy.rb",
     "lib/mongodoc/query.rb",
     "mongod.example.yml",
     "mongodoc.gemspec",
     "script/console",
     "spec/attributes_spec.rb",
     "spec/bson_matchers.rb",
     "spec/bson_spec.rb",
     "spec/collection_spec.rb",
     "spec/connection_spec.rb",
     "spec/criteria_spec.rb",
     "spec/cursor_spec.rb",
     "spec/document_ext.rb",
     "spec/document_spec.rb",
     "spec/mongodb.yml",
     "spec/mongodb_pairs.yml",
     "spec/parent_proxy_spec.rb",
     "spec/query_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/leshill/mongodoc}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{ODM for MongoDB}
  s.test_files = [
    "spec/attributes_spec.rb",
     "spec/bson_matchers.rb",
     "spec/bson_spec.rb",
     "spec/collection_spec.rb",
     "spec/connection_spec.rb",
     "spec/criteria_spec.rb",
     "spec/cursor_spec.rb",
     "spec/document_ext.rb",
     "spec/document_spec.rb",
     "spec/parent_proxy_spec.rb",
     "spec/query_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongo>, ["= 0.18.1"])
      s.add_runtime_dependency(%q<mongo_ext>, ["= 0.18.1"])
      s.add_runtime_dependency(%q<durran-validatable>, ["= 1.8.3"])
      s.add_runtime_dependency(%q<leshill-will_paginate>, ["= 2.3.11"])
      s.add_development_dependency(%q<rspec>, ["= 1.2.9"])
      s.add_development_dependency(%q<cucumber>, ["= 0.4.4"])
    else
      s.add_dependency(%q<mongo>, ["= 0.18.1"])
      s.add_dependency(%q<mongo_ext>, ["= 0.18.1"])
      s.add_dependency(%q<durran-validatable>, ["= 1.8.3"])
      s.add_dependency(%q<leshill-will_paginate>, ["= 2.3.11"])
      s.add_dependency(%q<rspec>, ["= 1.2.9"])
      s.add_dependency(%q<cucumber>, ["= 0.4.4"])
    end
  else
    s.add_dependency(%q<mongo>, ["= 0.18.1"])
    s.add_dependency(%q<mongo_ext>, ["= 0.18.1"])
    s.add_dependency(%q<durran-validatable>, ["= 1.8.3"])
    s.add_dependency(%q<leshill-will_paginate>, ["= 2.3.11"])
    s.add_dependency(%q<rspec>, ["= 1.2.9"])
    s.add_dependency(%q<cucumber>, ["= 0.4.4"])
  end
end

